src/routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

Route::prefix('admin')->group(function () {
    Auth::routes(['register' => false]);
});


Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['admin', 'auth']], function () {

    Route::post('/setstatus', 'Controller@SetStatus')->name('setstatus');

    Route::post('/change-order/{table}', 'IndexController@changeOrder')->name('change_order');
    Route::post('/change-lang', 'IndexController@changeLang')->name('change_lang');


    Route::get('/', 'IndexController@index')->name('dashboard');
    Route::get('/setting', 'IndexController@settings')->name('settings');


    Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
        Route::get('/', 'UserController@show')->name('show');
        Route::post('/', 'UserController@edit')->name('edit');
    });


    Route::group(['prefix' => 'const-field', 'as' => 'const_field.'], function () {
        Route::get('/', 'ConstFieldController@index')->name('index');
        Route::post('/', 'ConstFieldController@edit')->name('edit');
    });

    Route::group(['prefix' => 'smtp-settings', 'as' => 'smtp_settings.'], function () {
        Route::get('/', 'ConfigController@smtpSettingsIndex')->name('index');
        Route::post('/', 'ConfigController@smtpSettingsEdit')->name('edit');
    });

    Route::group(['prefix' => 'google-app-settings', 'as' => 'google_app_settings.'], function () {
        Route::get('/', 'ConfigController@googleAppSettingsIndex')->name('index');
        Route::post('/', 'ConfigController@googleAppSettingsEdit')->name('edit');
    });



    Route::group(['prefix' => 'pages', 'as' => 'page.'], function () {
        Route::get('/', 'PageController@index')->name('index');
        Route::get('/create', 'PageController@create')->name('create');
        Route::get('/{id}', 'PageController@show')->name('show');
        Route::post('/{id?}', 'PageController@edit')->name('edit');
        Route::get('/{id}/delete', 'PageController@delete')->name('delete');
    });


    Route::group(['prefix' => 'articles', 'as' => 'article.'], function () {
        Route::get('/', 'ArticleController@index')->name('index');
        Route::get('/create', 'ArticleController@create')->name('create');
        Route::get('/{id}', 'ArticleController@show')->name('show');
        Route::post('/{id?}', 'ArticleController@edit')->name('edit');
        Route::get('/{id}/delete', 'ArticleController@delete')->name('delete');
    });


    Route::group(['prefix' => 'article_categories', 'as' => 'article_category.'], function () {
        Route::get('/', 'ArticleCategoryController@index')->name('index');
        Route::get('/create', 'ArticleCategoryController@create')->name('create');
        Route::get('/{id}', 'ArticleCategoryController@show')->name('show');
        Route::post('/{id?}', 'ArticleCategoryController@edit')->name('edit');
        Route::get('/{id}/delete', 'ArticleCategoryController@delete')->name('delete');
    });


    Route::group(['prefix' => 'site_langs', 'as' => 'site_lang.'], function () {
        Route::get('/', 'SiteLangController@index')->name('index');
        Route::get('/create', 'SiteLangController@create')->name('create');
        Route::get('/{id}', 'SiteLangController@show')->name('show');
        Route::post('/{id?}', 'SiteLangController@edit')
            ->middleware('configCache')
            ->name('edit');
        Route::get('/{id}/delete', 'SiteLangController@delete')->name('delete');
    });


    Route::group(['prefix' => 'offers', 'as' => 'offer.'], function () {
        Route::get('/', 'OfferController@index')->name('index');
        Route::get('/create', 'OfferController@create')->name('create');
        Route::get('/{id}', 'OfferController@show')->name('show');
        Route::post('/{id?}', 'OfferController@edit')->name('edit');
        Route::get('/{id}/delete', 'OfferController@delete')->name('delete');
    });


    Route::group(['prefix' => 'offer_categories', 'as' => 'offer_category.'], function () {
        Route::get('/', 'OfferCategoryController@index')->name('index');
        Route::get('/create', 'OfferCategoryController@create')->name('create');
        Route::get('/{id}', 'OfferCategoryController@show')->name('show');
        Route::post('/{id?}', 'OfferCategoryController@edit')->name('edit');
        Route::get('/{id}/delete', 'OfferCategoryController@delete')->name('delete');
    });

    Route::group(['prefix' => 'rotator', 'as' => 'rotator.'], function () {
        Route::get('/', 'RotatorController@index')->name('index');
        Route::get('/create', 'RotatorController@create')->name('create');
        Route::get('/{id}', 'RotatorController@show')->name('show');
        Route::post('/{id?}', 'RotatorController@edit')->name('edit');
        Route::get('/{id}/delete', 'RotatorController@delete')->name('delete');
    });

    Route::group(['prefix' => 'realizations', 'as' => 'realization.'], function () {
        Route::get('/', 'RealizationController@index')->name('index');
        Route::get('/create', 'RealizationController@create')->name('create');
        Route::get('/{id}', 'RealizationController@show')->name('show');
        Route::post('/{id?}', 'RealizationController@edit')->name('edit');
        Route::get('/{id}/delete', 'RealizationController@delete')->name('delete');
    });


    Route::group(['prefix' => 'realization_categories', 'as' => 'realization_category.'], function () {
        Route::get('/', 'RealizationCategoryController@index')->name('index');
        Route::get('/create', 'RealizationCategoryController@create')->name('create');
        Route::get('/{id}', 'RealizationCategoryController@show')->name('show');
        Route::post('/{id?}', 'RealizationCategoryController@edit')->name('edit');
        Route::get('/{id}/delete', 'RealizationCategoryController@delete')->name('delete');
    });


    Route::group(['prefix' => 'nav-items', 'as' => 'nav_item.'], function () {
        Route::get('/{navName}/', 'NavItemController@index')->name('index');
        Route::get('/{navName}/create/{parentId?}', 'NavItemController@create')->name('create');
        Route::get('/{navName}/{id}', 'NavItemController@show')->name('show');
        Route::post('/{navName}/{id?}', 'NavItemController@edit')->name('edit');
        Route::get('/{navName}/{id}/delete', 'NavItemController@delete')->name('delete');
    });


});

src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



require_once('admin.php');





require_once('web_page.php');
require_once('web_article.php');
require_once('web_article_category.php');
require_once('web_offer.php');
require_once('web_offer_category.php');
require_once('web_realization.php');
require_once('web_realization_category.php');

src/app/Models/Offer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Offer extends BaseModel
{
    protected $table = 'offer';

    protected $fillable = [
        'offer_category_id',
        'title',
        'lead',
        'text',
        'position',
        'active',
    ];


    public function save(array $options = [])
    {
        return parent::saveWithPositionAndLang($options);
    }

    public function gallery() {
        return $this->belongsTo(Gallery::class);
    }

    public function categories() {
        return $this->belongsTo(OfferCategory::class);
    }
}

src/app/Http/Controllers/Admin/OfferController.php
<?php


namespace App\Http\Controllers\Admin;


use App\Forms\Admin\OfferForm;
use App\Forms\Admin\SeoForm;
use App\Http\Requests\Admin\OfferRequest;
use App\Models\Offer;
use App\Models\Gallery;

class OfferController extends BaseController
{
    public function __construct()
    {
        parent::__construct(
            Offer::class,
            OfferForm::class,
            'offer',
            true,
            true
        );
    }

    public function show(int $id) {
        $item = Offer::with(['seo', 'gallery'])->findOrFail($id);
        $form = new OfferForm($item);
        $formSeo = null;

        if($item->seo) {
            $formSeo = new SeoForm($item->seo);
        }

        if(!$item->gallery) {
            $item->gallery()->associate(Gallery::create());
            $item->save();
        }

        return view('admin.offer.edit', compact('item', 'form', 'formSeo'));
    }

    public function edit(OfferRequest $request)
    {
        return parent::baseEdit($request);
    }
}

src/app/Http/Controllers/OfferController.php
<?php


namespace App\Http\Controllers;


use App\Helpers\SeoHelper;
use App\Models\Offer;

class OfferController extends Controller
{
    public function show($item) {
        SeoHelper::setSeo($item->seo);

        return view('default.offer.show', compact('item'));
    }

    public function index($view) {
        $items = Offer::with([])
            ->activeAndLocale()
            ->orderByDesc('position')
            ->get();
        $view->items = $items;
    }

    public function home($view){
        $q = Offer::with([])
            ->activeAndLocale()
            ->orderByDesc('position');

        if($view->limit)
            $q->limit($view->limit);

        $items = $q->get();
        $view->items = $items;
    }

}

src/resources/views/admin/offer/category/edit.blade.php
@extends('admin.layout')
@section('content')

    <main>

        <form id="offer_category" method="POST" action="{{route('admin.offer_category.edit', $item)}}">
            @csrf

            <div class="row">
                <div class="col-lg-8">
                    <div class="card">
                        <div class="card-header">
                            <div>
                                <a href="{{route('admin.offer_category.index')}}"
                                   class="btn btn-secondary">{{__('admin.crud.back')}}</a>
                                @if($item->id)
                                    <a href="{{route('admin.offer_category.create')}}"
                                       class="btn btn-info">Utwórz nowy</a>
                                @endif
                            </div>
                            <div>
                                <button type="submit" form="offer_category"
                                        class="btn btn-success">{{__('admin.crud.'.($item->id ? 'save' : 'add'))}}</button>
                                <button type="submit" form="offer_category" name="saveandclose"
                                        class="btn btn-primary">{{__('admin.crud.'.($item->id ? 'save' : 'add'))}} i
                                    wyjdź
                                </button>
                            </div>
                        </div>
                        <div class="card-body">


                            {!! $form->renderFieldGroup('title') !!}
                            {!! $form->renderFieldGroup('lead') !!}
                            {!! $form->renderFieldGroup('text') !!}

                            <hr>
                            {!! $form->renderFieldGroup('active') !!}


                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    @include('admin.seo.partial', compact('formSeo'))
                </div>
            </div>

        </form>


        @if($item->id)
            @include('admin.gallery.partial', ['gallery' => $item->gallery])
        @endif

    </main>

@endsection

src/resources/views/admin/offer/category/index.blade.php
@extends('admin.layout')
@section('content')

    <main>

        <div class="card">
            <div class="card-header">
                {{__('admin.offer_category.plural')}}
                <a href="{{route('admin.offer_category.create')}}" class="btn btn-primary">{{__('admin.crud.create')}}</a>
            </div>
            <div class="card-body">
                <table class="table table-striped table-responsive-sm sortable" data-table="offer_category">
                    <thead>
                        <tr>
                            <td>#</td>
                            <td></td>
                            <td>{{__('admin.offer_category.title')}}</td>
                            <td>{{__('admin.active')}}</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                    @if(!$items->isEmpty())
                        @php($i = 1)
                        @foreach($items as $key=>$offer_category)
                            <tr data-id="{{$offer_category->id}}">
                                <td data-position>{{$i++}}</td>
                                <td style="width: 50px">
                                    <img src="{{renderSmallCover($offer_category)}}" alt="">
                                </td>
                                <td>
                                    {{$offer_category->title}}
                                    @if(isset($offer_category->seo))
                                        <small style="display: block">
                                            <a @if($offer_category->active) target="_blank" @else style="color: grey; opacity: .75" @endif href="@if($offer_category->active){{url()->to('')}}{{$offer_category->seo->url}}@else#@endif">
                                                {{str_replace(['https://', 'http://'], '', url()->to(''))}}{{$offer_category->seo->url}}
                                            </a>
                                        </small>
                                    @endif
                                </td>


                                <td>
                                    <input type="checkbox" class="status-switch" data-source_table="offer_category" data-source_id="{{$offer_category->id}}" {{$offer_category->active ? 'checked' : ''}}>
                                </td>
                                <td class="text-right text-nowrap">
                                    <a href="{{route('admin.offer_category.show', $offer_category)}}" class="btn btn-info btn-sm"><i data-feather="edit-2" class="mr-2"></i>{{__('admin.crud.edit')}}</a>
                                    <a href="{{route('admin.offer_category.delete', $offer_category)}}" class="btn btn-danger btn-sm"><i data-feather="trash" class="mr-2"></i>{{__('admin.crud.delete')}}</a>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="100">{{__('admin.empty_set')}}</td>
                        </tr>
                    @endif
                    </tbody>
                </table>

                {{$items->links()}}
            </div>
        </div>

    </main>

@endsection